version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    restart: always
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
