version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=mysql://root:mysql@db:3306/db
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
